workspace:
  path: testdata

pipeline:
  ## Build a test docker image
  build_docker:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t amarburg/covis-worker:latest -t amarburg/covis-worker:${DRONE_REPO_OWNER}-latest -t amarburg/covis-worker:${DRONE_REPO_OWNER}-${DRONE_COMMIT_SHA} .

  demo:
    image: amarburg/remote-compile:latest
    hosts: ssh-host
    user: root
    target: tempdir
    do_sleep: 10
    script:
      - ls -al
      - touch foo
    secrets: [ ssh_privkey ]

services:
  ssh-host:
    image: amarburg/drone-remote-compile-test-sshd
