workspace:
  path: testdata


## Must put private key in SSH_PRIVKEY
pipeline:
  demo:
    image: amarburg/remote-compile:latest
    hosts: ssh-host
    user: root
    target: tempdir
    do_sleep: 10
    script:
      - ls -al
      - touch foo
    secrets: [ ssh_privkey ]

services:
  ssh-host:
    image: amarburg/drone-remote-compile-test-sshd
